### ISSUE TITLE
CMake Generate fails under Windows

### ISSUE THREAD

**Issue by alpagani** [slightech/MYNT-EYE-SDK-2#1]
Hello

I try to generate the project with CMake under Windows, but it fails because the file uvc-wmf.cc is missing.
Can you please provide this file? Thanks
Al

**Comment by joinAero** [comment]
The SDK 2 only support Linux now. Windows will be supported about a week later.

**Comment by joinAero** [comment]
`uvc-wmf.cc` has been provided.
