### ISSUE TITLE
update firmware 2.0.0.-rc2 failed

### ISSUE THREAD

**Issue by ZhaoQiang2015** [slightech/MYNT-EYE-SDK-2#4]
when I update firmware 2.0.0.-rc2 it failed. and it say lack of Westbridge drive. I searched on the net but none find. could you provide it?

**Comment by ZhaoQiang2015** [comment]
this problem has been solved after I get the help with the after-sale service. : )

**Comment by pLesur** [comment]
@ZhaoQiang2015 Do you please remember what the fix was..?

**Comment by pLesur** [comment]
#48 fixed it
